[package]
name = "reversi-bevy"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18.0", default-features = false, features = ["2d"]}
reversi-core = { path = "../reversi-core" }
